In [1]:
import pandas as pd
import os
selected_files = [
    '/content/nba_player_stats_2026 2.csv',
    '/content/Advanced.csv',
    '/content/All-Star Selections.csv',
    '/content/Draft Pick History.csv',
    '/content/End of Season Teams (Voting).csv',
    '/content/End of Season Teams.csv',
    '/content/Opponent Stats Per 100 Poss.csv',
    '/content/Opponent Stats Per Game.csv',
    '/content/Opponent Totals.csv',
    '/content/Per 36 Minutes.csv',
    '/content/Per 100 Poss.csv',
    '/content/Player Award Shares.csv',
    '/content/Player Career Info.csv',
    '/content/Player Per Game.csv',
    '/content/Player Play By Play.csv',
    '/content/Player Season Info.csv',
    '/content/Player Shooting.csv',
    '/content/Player Totals.csv',
    '/content/Team Abbrev.csv',
    '/content/Team Stats Per 100 Poss.csv',
    '/content/Team Stats Per Game.csv',
    '/content/Team Summaries.csv',
    '/content/Team Totals.csv'
]

dfs = {}

for file_path in selected_files:
    try:
        # Extract filename without path and extension for dictionary key
        file_name = os.path.splitext(os.path.basename(file_path))[0]
        dfs[file_name] = pd.read_csv(file_path)
        print(f"Successfully loaded '{file_name}'")
    except Exception as e:
        print(f"Error loading '{file_path}': {e}")

Successfully loaded 'nba_player_stats_2026 2'
Successfully loaded 'Advanced'
Successfully loaded 'All-Star Selections'
Successfully loaded 'Draft Pick History'
Successfully loaded 'End of Season Teams (Voting)'
Successfully loaded 'End of Season Teams'
Successfully loaded 'Opponent Stats Per 100 Poss'
Successfully loaded 'Opponent Stats Per Game'
Successfully loaded 'Opponent Totals'
Successfully loaded 'Per 36 Minutes'
Successfully loaded 'Per 100 Poss'
Successfully loaded 'Player Award Shares'
Successfully loaded 'Player Career Info'
Successfully loaded 'Player Per Game'
Successfully loaded 'Player Play By Play'
Successfully loaded 'Player Season Info'
Successfully loaded 'Player Shooting'
Successfully loaded 'Player Totals'
Successfully loaded 'Team Abbrev'
Successfully loaded 'Team Stats Per 100 Poss'
Successfully loaded 'Team Stats Per Game'
Successfully loaded 'Team Summaries'
Successfully loaded 'Team Totals'

### Displaying the head of each loaded DataFrame

In [2]:
for name, df in dfs.items():
    print(f"\n--- Head of '{name}' DataFrame ---")
    display(df.head())

--- Head of 'nba_player_stats_2026 2' DataFrame ---

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1629029,1,Luka Dončić,1610612747,LAL,64,2289,693,1457,0.476,...,495,530,105,34,255,153,2143,2146,2.08,0.41
1,1628983,2,Shai Gilgeous-Alexander,1610612760,OKC,68,2259,731,1321,0.553,...,292,448,95,52,151,139,2117,2189,2.97,0.63
2,1627759,3,Jaylen Brown,1610612738,BOS,71,2443,736,1543,0.477,...,492,364,72,27,259,191,2038,1817,1.41,0.28
3,201142,4,Kevin Durant,1610612745,HOU,78,2840,716,1376,0.520,...,426,372,62,71,246,142,2026,1992,1.51,0.25
4,1630178,5,Tyrese Maxey,1610612755,PHI,70,2661,694,1501,0.462,...,290,461,130,55,171,151,1980,1893,2.70,0.76

--- Head of 'Advanced' DataFrame ---

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,tov_percent,usg_percent,ows,dws,ws,ws_48,obpm,dbpm,bpm,vorp
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,1745.0,...,9.0,17.6,1.8,1.2,2.9,0.081,-0.5,-1.1,-1.6,0.2
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,730.0,...,16.7,12.1,1.1,1.0,2.1,0.141,-0.1,-0.3,-0.5,0.3
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,2365.0,...,8.3,25.0,2.8,3.6,6.4,0.129,1.5,0.4,2.0,2.4
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,973.0,...,9.4,14.6,0.1,0.8,0.9,0.046,-3.5,-0.5,-4.0,-0.5
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,650.0,...,9.4,13.3,0.0,0.7,0.6,0.048,-4.8,0.1,-4.7,-0.5

--- Head of 'All-Star Selections' DataFrame ---

            player  player_id        team  season   lg  replaced
0   Scottie Barnes  barnesc01  Team Stars    2026  NBA     False
1     Devin Booker  bookede01  Team Stars    2026  NBA     False
2  Cade Cunningham  cunnica01  Team Stars    2026  NBA     False
3      Jalen Duren  durenja01  Team Stars    2026  NBA     False
4  Anthony Edwards  edwaran01  Team Stars    2026  NBA     False

--- Head of 'Draft Pick History' DataFrame ---

,season,lg,overall_pick,round,tm,player,player_id,college
0,2025,NBA,1.0,1.0,DAL,Cooper Flagg,flaggco01,Duke
1,2025,NBA,2.0,1.0,SAS,Dylan Harper,harpedy01,Rutgers University
2,2025,NBA,3.0,1.0,PHI,VJ Edgecombe,edgecvj01,Baylor
3,2025,NBA,4.0,1.0,CHO,Kon Knueppel,knuepko01,Duke
4,2025,NBA,5.0,1.0,UTA,Ace Bailey,baileac01,Rutgers University

--- Head of 'End of Season Teams (Voting)' DataFrame ---

,season,lg,type,number_tm,position,player,player_id,age,pts_won,pts_max,share,x1st_tm,x2nd_tm,x3rd_tm
0,2025,nba,all_defense,1st,F,Evan Mobley,mobleev01,23,199.0,200.0,0.995,NaN,NaN,NaN
1,2025,nba,all_defense,1st,G,Dyson Daniels,daniedy01,21,191.0,200.0,0.955,NaN,NaN,NaN
2,2025,nba,all_defense,1st,F,Luguentz Dort,dortlu01,25,180.0,200.0,0.900,NaN,NaN,NaN
3,2025,nba,all_defense,1st,F,Draymond Green,greendr01,34,179.0,200.0,0.895,NaN,NaN,NaN
4,2025,nba,all_defense,1st,F,Amen Thompson,thompam01,22,171.0,200.0,0.855,NaN,NaN,NaN

--- Head of 'End of Season Teams' DataFrame ---

   season   lg         type number_tm          player  player_id position
0    2025  NBA  All-Defense       1st   Dyson Daniels  daniedy01      NaN
1    2025  NBA  All-Defense       1st   Luguentz Dort   dortlu01      NaN
2    2025  NBA  All-Defense       1st  Draymond Green  greendr01      NaN
3    2025  NBA  All-Defense       1st     Evan Mobley  mobleev01      NaN
4    2025  NBA  All-Defense       1st   Amen Thompson  thompam01      NaN

--- Head of 'Opponent Stats Per 100 Poss' DataFrame ---

,season,lg,team,abbreviation,playoffs,g,mp,opp_fg_per_100_poss,opp_fga_per_100_poss,opp_fg_percent,...,opp_ft_percent,opp_orb_per_100_poss,opp_drb_per_100_poss,opp_trb_per_100_poss,opp_ast_per_100_poss,opp_stl_per_100_poss,opp_blk_per_100_poss,opp_tov_per_100_poss,opp_pf_per_100_poss,opp_pts_per_100_poss
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,41.5,87.7,0.474,...,0.794,10.9,33.4,44.3,26.1,8.3,4.8,15.7,18.1,113.7
1,2026,NBA,Boston Celtics,BOS,False,82,19730,40.3,91.3,0.442,...,0.775,11.4,31.9,43.3,26.0,6.5,4.3,13.1,19.3,112.7
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,43.3,87.0,0.497,...,0.775,10.4,34.3,44.7,28.2,9.4,5.5,14.9,20.0,119.0
3,2026,NBA,Chicago Bulls,CHI,False,82,19755,43.6,91.1,0.478,...,0.774,11.0,33.5,44.4,27.9,8.9,5.4,12.6,18.3,118.1
4,2026,NBA,Charlotte Hornets,CHO,False,82,19755,42.2,90.4,0.467,...,0.801,10.5,29.9,40.4,26.7,8.4,4.6,13.1,20.4,114.4

--- Head of 'Opponent Stats Per Game' DataFrame ---

,season,lg,team,abbreviation,playoffs,g,mp_per_game,opp_fg_per_game,opp_fga_per_game,opp_fg_percent,...,opp_ft_percent,opp_orb_per_game,opp_drb_per_game,opp_trb_per_game,opp_ast_per_game,opp_stl_per_game,opp_blk_per_game,opp_tov_per_game,opp_pf_per_game,opp_pts_per_game
0,2026,NBA,Atlanta Hawks,ATL,False,82.0,240.9,42.4,89.4,0.474,...,0.794,11.1,34.1,45.2,26.6,8.5,4.9,16.1,18.5,116.0
1,2026,NBA,Boston Celtics,BOS,False,82.0,240.6,38.4,86.8,0.442,...,0.775,10.9,30.4,41.2,24.7,6.2,4.1,12.4,18.4,107.2
2,2026,NBA,Brooklyn Nets,BRK,False,82.0,240.9,42.2,84.7,0.497,...,0.775,10.2,33.4,43.6,27.5,9.1,5.3,14.5,19.5,115.9
3,2026,NBA,Chicago Bulls,CHI,False,82.0,240.9,44.8,93.7,0.478,...,0.774,11.3,34.4,45.7,28.8,9.1,5.6,13.0,18.8,121.5
4,2026,NBA,Charlotte Hornets,CHO,False,82.0,240.9,41.0,87.9,0.467,...,0.801,10.2,29.1,39.3,25.9,8.2,4.4,12.7,19.8,111.2

--- Head of 'Opponent Totals' DataFrame ---

,season,lg,team,abbreviation,playoffs,g,mp,opp_fg,opp_fga,opp_fg_percent,...,opp_ft_percent,opp_orb,opp_drb,opp_trb,opp_ast,opp_stl,opp_blk,opp_tov,opp_pf,opp_pts
0,2026,NBA,Atlanta Hawks,ATL,False,82.0,19755.0,3473.0,7334.0,0.474,...,0.794,914.0,2796.0,3710.0,2185.0,695.0,402.0,1317.0,1515.0,9516.0
1,2026,NBA,Boston Celtics,BOS,False,82.0,19730.0,3145.0,7115.0,0.442,...,0.775,890.0,2489.0,3379.0,2029.0,505.0,339.0,1018.0,1508.0,8787.0
2,2026,NBA,Brooklyn Nets,BRK,False,82.0,19755.0,3457.0,6949.0,0.497,...,0.775,834.0,2739.0,3573.0,2254.0,750.0,436.0,1189.0,1595.0,9505.0
3,2026,NBA,Chicago Bulls,CHI,False,82.0,19755.0,3676.0,7687.0,0.478,...,0.774,925.0,2824.0,3749.0,2358.0,747.0,457.0,1063.0,1545.0,9964.0
4,2026,NBA,Charlotte Hornets,CHO,False,82.0,19755.0,3364.0,7207.0,0.467,...,0.801,835.0,2386.0,3221.0,2126.0,672.0,364.0,1041.0,1627.0,9117.0

--- Head of 'Per 36 Minutes' DataFrame ---

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,ft_percent,orb_per_36_min,drb_per_36_min,trb_per_36_min,ast_per_36_min,stl_per_36_min,blk_per_36_min,tov_per_36_min,pf_per_36_min,pts_per_36_min
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,1745,...,0.554,3.7,6.5,10.2,2.1,1.3,1.0,1.3,2.5,15.2
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,730,...,0.580,7.2,6.5,13.6,2.4,1.1,1.0,1.7,2.7,9.2
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,2365,...,0.778,2.3,8.9,11.1,3.5,1.3,0.7,1.8,1.9,22.3
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,973,...,0.837,1.7,3.5,5.2,1.7,0.9,0.6,1.1,3.4,11.6
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,650,...,0.862,1.8,3.4,5.3,1.7,0.9,0.6,1.1,4.2,10.0

--- Head of 'Per 100 Poss' DataFrame ---

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,drb_per_100_poss,trb_per_100_poss,ast_per_100_poss,stl_per_100_poss,blk_per_100_poss,tov_per_100_poss,pf_per_100_poss,pts_per_100_poss,o_rtg,d_rtg
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57.0,1745,...,8.7,13.6,2.8,1.8,1.4,1.8,3.4,20.4,117.0,119.0
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11.0,730,...,9.0,18.9,3.3,1.5,1.4,2.4,3.8,12.8,125.0,112.0
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73.0,2365,...,11.4,14.4,4.6,1.7,1.0,2.4,2.4,28.8,115.0,111.0
3,2026,NBA,Ochai Agbaji,agbajoc01,25,2TM,SG,62,13.0,973,...,4.8,7.1,2.4,1.2,0.9,1.6,4.7,15.8,108.0,117.0
4,2026,NBA,Ochai Agbaji,agbajoc01,25,TOR,SG,42,13.0,650,...,4.7,7.1,2.3,1.3,0.8,1.4,5.6,13.6,106.0,116.0

--- Head of 'Player Award Shares' DataFrame ---

,season,award,player,player_id,age,first,pts_won,pts_max,share,winner
0,2025,nba clutch_poy,Jalen Brunson,brunsja01,28,70.0,426.0,500.0,0.852,True
1,2025,nba clutch_poy,Nikola Jokić,jokicni01,29,26.0,312.0,500.0,0.624,False
2,2025,nba clutch_poy,Anthony Edwards,edwaran01,23,2.0,47.0,500.0,0.094,False
3,2025,nba clutch_poy,Trae Young,youngtr01,26,0.0,44.0,500.0,0.088,False
4,2025,nba clutch_poy,Stephen Curry,curryst01,36,1.0,27.0,500.0,0.054,False

--- Head of 'Player Career Info' DataFrame ---

,player,player_id,pos,ht_in_in,wt,birth_date,colleges,from,to,debut,hof
0,Hank Biasatti,biasaha01,G,71.0,175.0,1922-01-14,Assumption University,1947,1947,1946-11-01T00:00:00Z,False
1,Tommy Byrnes,byrneto01,F-G,75.0,175.0,1923-02-19,Seton Hall,1947,1951,1946-11-01T00:00:00Z,False
2,Bob Fitzgerald,fitzgbo01,F-C,77.0,190.0,1923-03-14,Seton Hall,1947,1949,1946-11-01T00:00:00Z,False
3,Dick Fitzgerald,fitzgdi01,F,74.0,175.0,1920-11-18,Fordham,1947,1948,1946-11-01T00:00:00Z,False
4,Frank Fucarino,fucarfr01,F,74.0,175.0,1920-07-24,Long Island University,1947,1947,1946-11-01T00:00:00Z,False

--- Head of 'Player Per Game' DataFrame ---

,season,lg,player,player_id,age,team,pos,g,gs,mp_per_game,...,ft_percent,orb_per_game,drb_per_game,trb_per_game,ast_per_game,stl_per_game,blk_per_game,tov_per_game,pf_per_game,pts_per_game
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,23.9,...,0.554,2.4,4.3,6.7,1.4,0.9,0.7,0.9,1.7,10.1
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,22.8,...,0.580,4.5,4.1,8.6,1.5,0.7,0.6,1.1,1.7,5.8
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,32.4,...,0.778,2.0,8.0,10.0,3.2,1.2,0.7,1.6,1.7,20.1
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,15.7,...,0.837,0.7,1.5,2.3,0.8,0.4,0.3,0.5,1.5,5.1
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,15.5,...,0.862,0.8,1.5,2.3,0.7,0.4,0.3,0.5,1.8,4.3

--- Head of 'Player Play By Play' DataFrame ---

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,net_plus_minus_per_100_poss,bad_pass_turnover,lost_ball_turnover,shooting_foul_committed,offensive_foul_committed,shooting_foul_drawn,offensive_foul_drawn,points_generated_by_assists,and1,fga_blocked
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,...,5.4,16,31,77,8,70,6.0,237,15,43
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,...,7.4,14,8,22,9,30,1.0,107,3,9
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,...,9.5,46,52,57,9,188,4.0,574,39,37
3,2026,NBA,Ochai Agbaji,agbajoc01,25,2TM,SG,62,13,973,...,-1.1,19,6,47,4,21,4.0,119,2,21
4,2026,NBA,Ochai Agbaji,agbajoc01,25,TOR,SG,42,13,650,...,-1.3,10,5,35,3,14,3.0,78,1,15

--- Head of 'Player Season Info' DataFrame ---

   season   lg              player  player_id   age team  pos  experience
0    1947  BAA      John Abramovic  abramjo01  27.0  PIT  NaN           1
1    1947  BAA       Chet Aubuchon  aubucch01  30.0  DTF  NaN           1
2    1947  BAA          Norm Baker  bakerno01  23.0  CHS  NaN           1
3    1947  BAA  Herschel Baltimore  baltihe01  25.0  STB  NaN           1
4    1947  BAA           John Barr   barrjo01  28.0  STB  NaN           1

--- Head of 'Player Shooting' DataFrame ---

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,fg_percent_from_x16_3p_range,fg_percent_from_x3p_range,percent_assisted_x2p_fg,percent_assisted_x3p_fg,percent_dunks_of_fga,num_of_dunks,percent_corner_3s_of_3pa,corner_3_point_percent,num_heaves_attempted,num_heaves_made
0,2026,NBA,Precious Achiuwa,achiupr01,26,SAC,C,73,57,1745,...,0.000,0.278,0.543,1.000,0.135,68,0.412,0.250,0,0
1,2026,NBA,Steven Adams,adamsst01,32,HOU,C,32,11,730,...,NaN,NaN,0.514,NaN,0.129,13,NaN,NaN,0,0
2,2026,NBA,Bam Adebayo,adebaba01,28,MIA,C,73,73,2365,...,0.308,0.318,0.612,0.961,0.079,81,0.313,0.320,0,0
3,2026,NBA,Ochai Agbaji,agbajoc01,25,2TM,SG,62,13,973,...,0.333,0.266,0.830,0.941,0.111,26,0.430,0.236,0,0
4,2026,NBA,Ochai Agbaji,agbajoc01,25,TOR,SG,42,13,650,...,0.000,0.185,0.783,1.000,0.141,19,0.523,0.206,0,0

--- Head of 'Player Totals' DataFrame ---

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,trp_dbl
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,1745.0,...,177.0,315.0,492.0,101,65.0,50.0,65.0,123.0,736,0.0
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,730.0,...,145.0,131.0,276.0,48,22.0,20.0,35.0,55.0,187,0.0
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,2365.0,...,149.0,583.0,732.0,232,86.0,49.0,120.0,122.0,1468,0.0
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,973.0,...,46.0,95.0,141.0,47,24.0,17.0,31.0,93.0,314,0.0
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,650.0,...,33.0,62.0,95.0,30,17.0,11.0,19.0,75.0,181,0.0

--- Head of 'Team Abbrev' DataFrame ---

   season   lg               team abbreviation  playoffs
0    2026  NBA      Atlanta Hawks          ATL     False
1    2026  NBA     Boston Celtics          BOS     False
2    2026  NBA      Brooklyn Nets          BRK     False
3    2026  NBA      Chicago Bulls          CHI     False
4    2026  NBA  Charlotte Hornets          CHO     False

--- Head of 'Team Stats Per 100 Poss' DataFrame ---

,season,lg,team,abbreviation,playoffs,g,mp,fg_per_100_poss,fga_per_100_poss,fg_percent,...,ft_percent,orb_per_100_poss,drb_per_100_poss,trb_per_100_poss,ast_per_100_poss,stl_per_100_poss,blk_per_100_poss,tov_per_100_poss,pf_per_100_poss,pts_per_100_poss
0,2026,NBA,Atlanta Hawks,ATL,False,82,19755,42.7,90.1,0.474,...,0.774,10.8,31.9,42.7,29.5,9.2,4.6,13.9,19.3,116.1
1,2026,NBA,Boston Celtics,BOS,False,82,19730,44.3,94.9,0.467,...,0.807,13.1,35.6,48.8,25.9,7.5,5.3,13.0,20.0,120.8
2,2026,NBA,Brooklyn Nets,BRK,False,82,19755,38.4,86.8,0.443,...,0.780,10.6,29.8,40.4,25.7,8.2,4.4,16.2,21.6,108.7
3,2026,NBA,Chicago Bulls,CHI,False,82,19755,41.2,87.9,0.469,...,0.776,10.1,33.7,43.8,27.7,7.4,4.9,14.9,18.5,113.0
4,2026,NBA,Charlotte Hornets,CHO,False,82,19755,42.1,91.5,0.460,...,0.818,13.2,34.3,47.4,27.1,7.2,4.6,15.9,19.6,119.4

--- Head of 'Team Stats Per Game' DataFrame ---

,season,lg,team,abbreviation,playoffs,g,mp_per_game,fg_per_game,fga_per_game,fg_percent,...,ft_percent,orb_per_game,drb_per_game,trb_per_game,ast_per_game,stl_per_game,blk_per_game,tov_per_game,pf_per_game,pts_per_game
0,2026,NBA,Atlanta Hawks,ATL,False,82.0,240.9,43.6,92.0,0.474,...,0.774,11.0,32.6,43.5,30.1,9.4,4.7,14.2,19.7,118.5
1,2026,NBA,Boston Celtics,BOS,False,82.0,240.6,42.1,90.2,0.467,...,0.807,12.5,33.9,46.4,24.6,7.1,5.0,12.4,19.0,114.9
2,2026,NBA,Brooklyn Nets,BRK,False,82.0,240.9,37.5,84.5,0.443,...,0.780,10.3,29.0,39.3,25.0,8.0,4.3,15.8,21.1,105.9
3,2026,NBA,Chicago Bulls,CHI,False,82.0,240.9,42.4,90.5,0.469,...,0.776,10.4,34.7,45.0,28.5,7.6,5.0,15.3,19.0,116.3
4,2026,NBA,Charlotte Hornets,CHO,False,82.0,240.9,40.9,88.9,0.460,...,0.818,12.8,33.3,46.1,26.3,7.0,4.5,15.4,19.1,116.0

--- Head of 'Team Summaries' DataFrame ---

,season,lg,team,abbreviation,playoffs,age,w,l,pw,pl,...,tov_percent,orb_percent,ft_fga,opp_e_fg_percent,opp_tov_percent,drb_percent,opp_ft_fga,arena,attend,attend_g
0,2026,NBA,Atlanta Hawks,ATL,False,25.2,46.0,36.0,47.0,35.0,...,12.3,24.4,0.181,0.546,13.9,74.5,0.206,State Farm Arena,670581.0,16356.0
1,2026,NBA,Boston Celtics,BOS,False,26.9,56.0,26.0,59.0,23.0,...,11.2,29.2,0.167,0.523,11.4,75.7,0.189,TD Garden,785396.0,19156.0
2,2026,NBA,Brooklyn Nets,BRK,False,23.5,20.0,62.0,18.0,64.0,...,14.3,23.6,0.212,0.571,13.2,74.0,0.225,Barclays Center,713896.0,17412.0
3,2026,NBA,Chicago Bulls,CHI,False,25.3,31.0,51.0,29.0,53.0,...,13.3,23.1,0.191,0.553,11.1,75.5,0.190,United Center,829997.0,20244.0
4,2026,NBA,Charlotte Hornets,CHO,False,24.0,44.0,38.0,53.0,29.0,...,13.5,30.5,0.200,0.540,11.6,76.6,0.186,Spectrum Center,767319.0,18715.0

--- Head of 'Team Totals' DataFrame ---

,season,lg,team,abbreviation,playoffs,g,mp,fg,fga,fg_percent,...,ft_percent,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,2026,NBA,Atlanta Hawks,ATL,False,82.0,19755.0,3575.0,7541.0,0.474,...,0.774,900.0,2670.0,3570.0,2471.0,768.0,384.0,1162.0,1612.0,9714.0
1,2026,NBA,Boston Celtics,BOS,False,82.0,19730.0,3456.0,7398.0,0.467,...,0.807,1025.0,2777.0,3802.0,2021.0,585.0,410.0,1014.0,1562.0,9418.0
2,2026,NBA,Brooklyn Nets,BRK,False,82.0,19755.0,3071.0,6933.0,0.443,...,0.780,847.0,2378.0,3225.0,2050.0,653.0,350.0,1292.0,1728.0,8686.0
3,2026,NBA,Chicago Bulls,CHI,False,82.0,19755.0,3476.0,7417.0,0.469,...,0.776,849.0,2845.0,3694.0,2335.0,627.0,410.0,1257.0,1561.0,9537.0
4,2026,NBA,Charlotte Hornets,CHO,False,82.0,19755.0,3357.0,7292.0,0.460,...,0.818,1048.0,2730.0,3778.0,2160.0,577.0,369.0,1264.0,1564.0,9513.0